### ISSUE TITLE
Free Event Ticket Website Alternative

### ISSUE THREAD

**Issue by DarwinJS** [devops-collective-inc/powershell-saturday#2]
I recently went through almost all the SaaS options for selling event tickets for my daughter's school - a huge criteria was "free or close to it".

Comparing the pricing models is like comparing apples to snowflakes - there seems to be no two alike.

http://yapsody.com had the most features for free.  They only charge if you want the "reserved seating" feature, which probably isn't relevant to these types of events anyway.

You still pay credit card fees to whomever you pick for credit card processing - but nothing for the event and ticket processing.  If you are doing your event under the umbrella of an official non-profit - see #3 about free credit card processing.

Yapsody is not super intuitive either - but they readily help with live chat help and take feature suggestions.

They are not an event marketplace like eventbrite.com, so you don't get an in feed of people "just looking for cool events" - but it seems to me most of eventbrite's cross sell would be for leisure, not work events anyway.

**Comment by jdhitsolutions** [comment]
Thanks for your thoughts Darren. For the DevOps Collective there are other factors outside of this initiative that tie into our decision to use Eventbrite. But certainly, if PowerShell Saturday organizers want to handle all of the finances themselves and control the money, they certainly can which means they can use any service they'd like.  We're hoping our assistance can help kick-start a number of events.
