### ISSUE TITLE
Credit Card Processing for Free for Non-profits

### ISSUE THREAD

**Issue by DarwinJS** [devops-collective-inc/powershell-saturday#3]
In conjunction with #2, I was able to get free credit card processing from stripe.com for the first year or $15,000.  For USA non-profits you must send your official 401c3 approval letter.  I'm not sure about other countries - but they are UK based so may have criteria for others.

It is a human based approval process so the terms may change or be based on what kind of non-profit you are - not sure.

Information here: https://support.stripe.com/questions/does-stripe-offer-a-fee-discount-for-non-profit-organizations

**Comment by concentrateddon** [comment]
We looked into that and, because we're obviously in it for more than a year (and burn way more than $15k) is wasn't reasonable. Honestly, the CC fees aren't a huge burden - the bigger deal is in becoming a nonprofit so that you can roll revenue from year to year without paying taxes on it.

**Comment by DarwinJS** [comment]
@concentrateddon - I forgot to mention that even after this initial period, you end up at a discounted rate below the list price.

**Comment by concentrateddon** [comment]
EventBrite extends a similar discount for nonprofits. As Jeff mentioned on the other issue, we have a lot of other factors that drive us to EventBrite, including Sched and MailChimp integration, which are necessary to run Summit. For PowerShell Saturday, I think it's important to remember that the organizers won't be forming nonprofit corporations - our offer to run the finances through us stems from that, but we're not looking to change our provider set at the moment.
