### ISSUE TITLE
Include a Simple Business Plan Template

### ISSUE THREAD

**Issue by michaeltlombardi** [devops-collective-inc/powershell-saturday#4]
The [current documentation](https://github.com/devops-collective-inc/powershell-saturday/wiki/Business-Plan/4b069ace8d8db66ed9144f3a50ed4bbd2ca2a057) does a really good job of explaining _what_ to figure out and write but doesn't provide much information on format.

I don't know if that even matters (or if I can just have a file with those headings/information), but it'd be a relatively simple addition for pushing people into the pit of success.

**Comment by jdhitsolutions** [comment]
I think a document with the appropriate headings is all that is required. I hesitate to constrain people to a template if that is what you are suggesting.

**Comment by michaeltlombardi** [comment]
Nope, exactly that advice (a document with the appropriate headings) is all I thought might be useful for people. Just providing a markdown template to that effect might be useful.

**Comment by jdhitsolutions** [comment]
Except this is not an online process. Still....I can recognize the value. Let me see what I can do.

**Comment by michaeltlombardi** [comment]
I'm happy to do up a simple one and submit. There's a bunch of utilities for transcribing markdown to PDF/DOCX/etc.

**Comment by jdhitsolutions** [comment]
We don't have any hard and fast rules about the document as long as it provides the relevant information. If people want, MS Word has a number of business plan templates that can be downloaded as a starting guide.

**Comment by michaeltlombardi** [comment]
Didn't know about those, either. Might be easier to just update the business plan section with suggestions on that, then. I was googling for templates prior to filing this issue.

**Comment by jdhitsolutions** [comment]
I modified the Business Plan wiki page.

**Comment by michaeltlombardi** [comment]
Perfect! That resolves the need as far as I can tell!
